server:
  port: 8097

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-70696276.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaedqhxuzyakiDSc5d7
    client-secret: cgDttVlRqp5JEdP5_BN60YzH_TuNDzuOghibWvKS-GbRchBEFUhJYeWlrkJ4ejq6
    scopes: openid, profile, email, offline_access